version: '2'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    - "3001:3001"
    command:
      npm run start
    depends_on:
    - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    command:
      node index.js
    depends_on:
    - elasticsearch
    - nginx
  elasticsearch:
    image: elasticsearch
    command: elasticsearch -Des.network.bind_host=0.0.0.0
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - ./system-containers/elasticsearch/data:/usr/share/elasticsearch/data
    - ./system-containers/elasticsearch/config/scripts:/usr/share/elasticsearch/config
  nginx:
    image: nginx
    ports:
    - "80:80"
    volumes:
    - ./system-containers/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro